title: "Learn Wgpu(ja)"
summary: "Learn Wgpuの非公式日本語訳です"
topics: ["rust", "wgpu", "webgpu"]
published: true
price: 0 

chapters:
  - intro
  - dependencies-and-window
  - surface
  - pipeline
  - buffer-and-indices
  - textures-and-bind-groups
#  - uniforms